name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: ["3.10", "3.12"]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Run Cybersecurity Benchmark Tests
        run: CybersecurityBenchmarks/scripts/run_tests.sh

      - name: Run LlamaFirewall Tests
        run: LlamaFirewall/scripts/run_tests.sh
